;;;; package.lisp

(defpackage #:rman
  (:use #:cl)
  (:export
   #:null-wrapper
   #:symbol-append
   #:null-wrapped
   #:null-wrapped-rest
   #:RI_NULL
   #:RI_FALSE
   #:RI_TRUE
   #:RI_INFINITY
   #:RI_EPSILON
   #:RI_FRAMEBUFFER
   #:RI_FILE
   #:RI_ZFILE
   #:RI_RGB
   #:RI_RGBA
   #:RI_RGBZ
   #:RI_RGBAZ
   #:RI_A
   #:RI_Z
   #:RI_AZ
   #:RI_PERSPECTIVE
   #:RI_ORTHOGRAPHIC
   #:RI_HIDDEN
   #:RI_PAINT
   #:RI_RAYTRACE
   #:RI_PHOTON
   #:RI_CONSTANT
   #:RI_SMOOTH
   #:RI_FLATNESS
   #:RI_FOV
   #:RI_AMBIENTLIGHT
   #:RI_POINTLIGHT
   #:RI_DISTANTLIGHT
   #:RI_SPOTLIGHT
   #:RI_INTENSITY
   #:RI_LIGHTCOLOR
   #:RI_FROM
   #:RI_TO
   #:RI_CONEANGLE
   #:RI_CONEDELTAANGLE
   #:RI_BEAMDISTRIBUTION
   #:RI_MATTE
   #:RI_METAL
   #:RI_SHINYMETAL
   #:RI_PLASTIC
   #:RI_PAINTEDPLASTIC
   #:RI_KA
   #:RI_KD
   #:RI_KS
   #:RI_ROUGHNESS
   #:RI_KR
   #:RI_TEXTURENAME
   #:RI_SPECULARCOLOR
   #:RI_DEPTHCUE
   #:RI_FOG
   #:RI_BUMPY
   #:RI_MINDISTANCE
   #:RI_MAXDISTANCE
   #:RI_BACKGROUND
   #:RI_DISTANCE
   #:RI_AMPLITUDE
   #:RI_RASTER
   #:RI_SCREEN
   #:RI_CAMERA
   #:RI_WORLD
   #:RI_OBJECT
   #:RI_INSIDE
   #:RI_OUTSIDE
   #:RI_LH
   #:RI_RH
   #:RI_P
   #:RI_PZ
   #:RI_PW
   #:RI_N
   #:RI_NP
   #:RI_CS
   #:RI_OS
   #:RI_S
   #:RI_T
   #:RI_ST
   #:RI_BILINEAR
   #:RI_BICUBIC
   #:RI_PRIMITIVE
   #:RI_INTERSECTION
   #:RI_UNION
   #:RI_DIFFERENCE
   #:RI_PERIODIC
   #:RI_NONPERIODIC
   #:RI_CLAMP
   #:RI_BLACK
   #:RI_IGNORE
   #:RI_PRINT
   #:RI_ABORT
   #:RI_HANDLER
   #:RI_BOUNDS
   #:RI_LIMITS
   #:RI_SHADOW
   #:RI_BIAS0
   #:RI_BIAS1
   #:RI_SAMPLE
   #:RI_SEARCHPATH
   #:RI_SHADER
   #:RI_TEXTURE
   #:RI_DISPLAY
   #:RI_WIDTH
   #:RI_CONSTANTWIDTH
   #:RI_COMMENT
   #:RI_STRUCTURE
   #:RI_VERBATIM
   #:RI_IDENTIFIER
   #:RI_NAME
   #:RI_SHADINGGROUP
   #:RI_LINEAR
   #:RI_CUBIC
   #:RI_BUCKETSENDER
   #:RI_FUNCTION
   #:RI_THRESHOLD
   #:RI___THRESHOLD
   #:RI_HANDLEID
   #:RI___HANDLEID
   #:RI_ASYNCHRONOUS_RENDER
   #:RI_FINISHRENDERING
   #:RI_SUSPENDRENDERING
   #:RI_STREAMMARKER
   #:RI_QUANTIZE
   #:RI_DITHER
   #:RI_EXPOSURE
   #:RI_FILTER
   #:RI_FILTERWIDTH

   #:RiBezierBasis
   #:RiBSplineBasis
   #:RiCatmullRomBasis
   #:RiHermiteBasis
   #:RiPowerBasis

   #:RI_BEZIERSTEP
   #:RI_BSPLINESTEP
   #:RI_CATMULLROMSTEP
   #:RI_HERMITESTEP
   #:RI_POWERSTEP

   #:RiBegin
   #:RiEnd
   #:RiGetContext
   #:RiContext
   #:RiFrameBegin
   #:RiFrameEnd
   #:RiMotionBegin
   #:RiMotionBeginV
   #:RiMotionEnd
   #:RiSolidBegin
   #:RiSolidEnd
   #:RiWorldBegin
   #:RiWorldEnd
   #:RiObjectBegin
   #:RiObjectBeginV
   #:RiObjectEnd
   #:RiObjectInstance
   #:RiResource
   #:RiResourceV
   #:RiResourceBegin
   #:RiResourceEnd
   #:RiFormat
   #:RiFrameAspectRatio
   #:RiScreenWindow
   #:RiClipping
   #:RiClippingPlane
   #:RiCropWindow
   #:RiDepthOfField
   #:RiProjection
   #:RiProjectionV
   #:RiShutter
   #:RiCamera
   #:RiCameraV
   #:RiDisplay
   #:RiDisplayV
   #:RiDisplayChannel
   #:RiDisplayChannelV
   #:RiExposure
   #:RiImager
   #:RiImagerV
   #:RiPixelFilter
   #:RiPixelSamples
   #:RiPixelVariance
   #:RiQuantize
   #:RiConcatTransform
   #:RiCoordinateSystem
   #:RiScopedCoordinateSystem
   #:RiCoordSysTransform
   #:RiIdentity
   #:RiPerspective
   #:RiRotate
   #:RiScale
   #:RiSkew
   #:RiTransform
   #:RiTransformBegin
   #:RiTransformEnd
   #:RiTranslate
   #:RiTransformPoints
   #:RiAtmosphere
   #:RiAtmosphereV
   #:RiDeformation
   #:RiDeformationV
   #:RiDisplacement
   #:RiDisplacementV
   #:RiExterior
   #:RiExteriorV
   #:RiIlluminate
   #:RiInterior
   #:RiInteriorV
   #:RiShader
   #:RiShaderV
   #:RiMatte
   #:RiMultiplyShadingRate
   #:RiShadingRate
   #:RiShadingInterpolation
   #:RiSurface
   #:RiSurfaceV
   #:RiArchiveRecord
   #:RiReadArchive
   #:RiReadArchiveV
   #:RiArchiveBegin
   #:RiArchiveBeginV
   #:RiArchiveEnd
   #:RiIfBegin
   #:RiIfBeginV
   #:RiElseIf
   #:RiElseIfV
   #:RiElse
   #:RiIfEnd
   #:RiAttribute
   #:RiAttributeV
   #:RiAttributeBegin
   #:RiAttributeEnd
   #:RiBound
   #:RiColor
   #:RiOpacity
   #:RiOption
   #:RiOptionV
   #:RiReverseOrientation
   #:RiTextureCoordinates
   #:RiSides
   #:RiDeclare
   #:RiLightSource
   #:RiLightSourceV
   #:RiAreaLightSource
   #:RiAreaLightSourceV
   #:RiBasis
   #:RiPatch
   #:RiPatchMesh
   #:RiPatchV
   #:RiPatchMeshV
   #:RiPoints
   #:RiPointsV
   #:RiCurves
   #:RiCurvesV
   #:RiNuCurves
   #:RiNuCurvesV
   #:RiNuPatch
   #:RiNuPatchV
   #:RiTrimCurve
   #:RiSubdivisionMesh
   #:RiSubdivisionMeshV
   #:RiHierarchicalSubdivisionMesh
   #:RiHierarchicalSubdivisionMeshV
   #:RiCone
   #:RiConeV
   #:RiCylinder
   #:RiCylinderV
   #:RiDisk
   #:RiDiskV
   #:RiHyperboloid
   #:RiHyperboloidV
   #:RiParaboloid
   #:RiParaboloidV
   #:RiSphere
   #:RiSphereV
   #:RiTorus
   #:RiTorusV
   #:RiGeneralPolygon
   #:RiGeneralPolygonV
   #:RiBlobby
   #:RiBlobbyV
   #:RiPointsGeneralPolygons
   #:RiPointsGeneralPolygonsV
   #:RiPointsPolygons
   #:RiPointsPolygonsV
   #:RiPolygon
   #:RiPolygonV
   #:RiColorSamples
   #:RiHider
   #:RiHiderV
   #:RiDetail
   #:RiDetailRange
   #:RiGeometricApproximation
   #:RiGeometry
   #:RiGeometryV
   #:RiOrientation
   #:RiProcedural
   #:RiProceduralV
   #:RiRelativeDetail
   #:RiProcDelayedReadArchive
   #:RiProcDynamicLoad
   #:RiProcRunProgram
   #:RiProcFree
   #:RiMakeBump
   #:RiMakeBumpV
   #:RiMakeCubeFaceEnvironment
   #:RiMakeCubeFaceEnvironmentV
   #:RiMakeLatLongEnvironment
   #:RiMakeLatLongEnvironmentV
   #:RiMakeShadow
   #:RiMakeShadowV
   #:RiMakeTexture
   #:RiMakeTextureV
   #:RiMakeBrickMap
   #:RiMakeBrickMapV
   #:RiBoxFilter
   #:RiTriangleFilter
   #:RiCatmullRomFilter
   #:RiSeparableCatmullRomFilter
   #:RiBesselFilter
   #:RiGaussianFilter
   #:RiSincFilter
   #:RiBlackmanHarrisFilter
   #:RiMitchellFilter
   #:RiDiskFilter
   #:RiErrorHandler
   #:RiErrorIgnore
   #:RiErrorPrint
   #:RiErrorAbort
   #:RiSynchronize
   #:RiEditBegin
   #:RiEditBeginV
   #:RiEditEnd
   #:RiEditWorldBegin
   #:RiEditWorldBeginV
   #:RiEditWorldEnd
   ))
